# https://github.com/brainupgrade-in/request-logger/blob/main/.ado/maven-package-junit.yml
trigger: none

pool:
  #  vmImage: 'ubuntu-latest'
  name: selfhosted

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  env:
    JAVA_HOME_11_X64: "/usr/lib/jvm/java-11-openjdk-amd64"
    PATH: "/usr/lib/jvm/java-11-openjdk-amd64/bin:$(PATH)"     